# Generated by Django 4.0.1 on 2022-01-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
