# Generated by Django 4.0.1 on 2022-01-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userverification_expires_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiToken',
        ),
    ]
