export const authConstant = { 
  
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_LOADING: 'USER_LOGIN_LOADING',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',

  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',

  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILED: 'USER_REGISTER_FAILED',
  USER_REGISTER_LOADING: 'USER_REGISTER_LOADING'

};
