export const linkConstant = { 

  FETCH_USER_LINK_LOADING: 'FETCH_USER_LINK_LOADING',
  FETCH_USER_LINK_SUCCESS: 'FETCH_USER_LINK_SUCCESS',
  FETCH_USER_LINK_FAILED: 'FETCH_USER_LINK_FAILED',

  CREATE_USER_LINK_LOADING: 'CREATE_USER_LINK_LOADING',
  CREATE_USER_LINK_SUCCESS: 'CREATE_USER_LINK_SUCCESS',
  CREATE_USER_LINK_FAILED: 'CREATE_USER_LINK_FAILED',

  FETCH_USER_LINK_OBJECT_LOADING: 'FETCH_USER_LINK_OBJECT_LOADING',
  FETCH_USER_LINK_OBJECT_SUCCESS: 'FETCH_USER_LINK_OBJECT_SUCCESS',
  FETCH_USER_LINK_OBJECT_FAILED: 'FETCH_USER_LINK_OBJECT_FAILED',

};
