export const linkConstant = { 

  FETCH_USER_LINK_LOADING: 'FETCH_USER_LINK_LOADING',
  FETCH_USER_LINK_SUCCESS: 'FETCH_USER_LINK_SUCCESS',
  FETCH_USER_LINK_FAILED: 'FETCH_USER_LINK_FAILED',

  CREATE_USER_LINK_LOADING: 'CREATE_USER_LINK_LOADING',
  CREATE_USER_LINK_SUCCESS: 'CREATE_USER_LINK_SUCCESS',
  CREATE_USER_LINK_FAILED: 'CREATE_USER_LINK_FAILED',

  FETCH_USER_LINK_OBJECT_LOADING: 'FETCH_USER_LINK_OBJECT_LOADING',
  FETCH_USER_LINK_OBJECT_SUCCESS: 'FETCH_USER_LINK_OBJECT_SUCCESS',
  FETCH_USER_LINK_OBJECT_FAILED: 'FETCH_USER_LINK_OBJECT_FAILED',

  DELETE_USER_LINK_OBJECT_LOADING: 'DELETE_USER_LINK_OBJECT_LOADING',
  DELETE_USER_LINK_OBJECT_SUCCESS: 'DELETE_USER_LINK_OBJECT_SUCCESS',
  DELETE_USER_LINK_OBJECT_FAILED: 'DELETE_USER_LINK_OBJECT_FAILED',

  EDIT_USER_LINK_OBJECT_LOADING: 'EDIT_USER_LINK_OBJECT_LOADING',
  EDIT_USER_LINK_OBJECT_SUCCESS: 'EDIT_USER_LINK_OBJECT_SUCCESS',
  EDIT_USER_LINK_OBJECT_FAILED: 'EDIT_USER_LINK_OBJECT_FAILED',

  GET_SHARE_LINK_OBJECT_LOADING: 'GET_SHARE_LINK_OBJECT_LOADING',
  GET_SHARE_LINK_OBJECT_SUCCESS: 'GET_SHARE_LINK_OBJECT_SUCCESS',
  GET_SHARE_LINK_OBJECT_FAILED: 'GET_SHARE_LINK_OBJECT_FAILED',

};
