# Generated by Django 4.0.1 on 2022-01-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
