# Generated by Django 4.0.1 on 2022-01-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner_api', '0002_userurl_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userurl',
            name='facebook_click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userurl',
            name='linkedin_click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userurl',
            name='twitter_click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userurl',
            name='whatsapp_click',
            field=models.IntegerField(default=0),
        ),
    ]
