# Generated by Django 4.0.1 on 2022-01-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner_api', '0004_socialmediaplatformlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaplatformlink',
            name='rgb_code',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
